### ISSUE TITLE
Buildbot fails

### ISSUE THREAD

**Issue by halton** [01org/node-realsense#180]
https://travis-ci.org/01org/node-realsense/builds/215436218

**Comment by kenny-y** [comment]
https://travis-ci.org/01org/node-realsense/builds/215436218#L2118

```
  CXX(target) Release/obj.target/realsense_object_recognition/common/camera-delegate/camera_delegate.o

In file included from ../common/camera-delegate/camera_delegate.cpp:5:0:

../common/camera-delegate/camera_delegate.h:8:31: fatal error: librealsense/rs.hpp: No such file or directory

compilation terminated.
```

`librealsense` headers should be already installed... what is going on, I wonder...

**Comment by tingshao** [comment]
In fact, it was not installed.
I went through and compared some of the failed and succeeded builds.
failed builds like this one, is due to:
`Err:115 http://realsense-alm-public.s3.amazonaws.com/apt-repo xenial/main amd64 librealsense-slam2 amd64 2.0.4-0ubuntu1~25.gbp73dfd6
  Hash Sum mismatch`
this failure to download the package cause most of the realsense related packages not installed.

A previous failure of build No 33, is caused by hash mismatch when downloading librealsense-samples package:
`Err:116 http://realsense-alm-public.s3.amazonaws.com/apt-repo xenial/main amd64 librealsense-samples amd64 0.6.5-1ubuntu1~21.gbp8e624e
  Hash Sum mismatch`

**Comment by halton** [comment]
Checked with @tingshao for recent buildbot logs at https://travis-ci.org/01org/node-realsense/builds, this failure is occasionally happening.  So close it as not fix.
